"""
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
triangle
 
p3,n=n(n+1)/2
 
1, 3, 6, 10, 15, ...
square
 
p4,n=n2
 
1, 4, 9, 16, 25, ...
pentagonal
 
p5,n=n(3n1)/2
 
1, 5, 12, 22, 35, ...
hexagonal
 
p6,n=n(2n1)
 
1, 6, 15, 28, 45, ...
heptagonal
 
p7,n=n(5n3)/2
 
1, 7, 18, 34, 55, ...
octagonal
 
p8,n=n(3n2)
 
1, 8, 21, 40, 65, ...
the ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
the set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
each polygonal type: triangle (p3,127=8128), square (p4,91=8281), and pentagonal (p5,44=2882), is represented by a different number in the set.
this is the only set of 4-digit numbers with this property.
find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
"""