"""
Each new term in the fibonacci sequence is generated by adding the previous two terms.
starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.

every positive integer can be uniquely written as a sum of nonconsecutive terms of the fibonacci sequence. for example, 100 = 3 + 8 + 89.
such a sum is called the zeckendorf representation of the number.

for any integer n>0, let z(n) be the number of terms in the zeckendorf representation of n.
thus, z(5) = 1, z(14) = 2, z(100) = 3 etc.
also, for 0n106, ∑ z(n) = 7894453.

find ∑ z(n) for 0n1017.
"""