"""
Pentagonal numbers are generated by the formula, pn=n(3n1)/2. the first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
it can be seen that p4 + p7 = 22 + 70 = 92 = p8. however, their difference, 70  22 = 48, is not pentagonal.
find the pair of pentagonal numbers, pj and pk, for which their sum and difference is pentagonal and d = |pk pj| is minimised; what is the value of d?
"""