"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
triangle
 
tn=n(n+1)/2
 
1, 3, 6, 10, 15, ...
pentagonal
 
pn=n(3n1)/2
 
1, 5, 12, 22, 35, ...
hexagonal
 
hn=n(2n1)
 
1, 6, 15, 28, 45, ...
it can be verified that t285 = p165 = h143 = 40755.
find the next triangle number that is also pentagonal and hexagonal.
"""